[package]
name = "bot-animem-uz"
version = "0.1.0"
description = "Animem Uz Web App"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
public = "dist"

[[command]]
name = "webserver"
module = "wasmer/static-web-server:webserver"
runner = "wasi"

[app]
public = true

[[app.routes]]
path = "/*"
backend = "command:webserver"
