[package]
name = "bot-animem-uz"
version = "0.1.0"
description = "Anime Backend App"

[[module]]
name = "server"
source = "build_output/server.cjs"

[[command]]
name = "run"
module = "server"
runner = "wasmer/js"

[app]
public = true

[[app.routes]]
path = "/*"
backend = "command:run"
