-- ==========================================================
-- KAWAI / ANIMEM POSTGRESQL TO'LIQ DUMP VA DDL STRUKTURASI
-- Wasmer DB Explorer (Adminer) uchun SQL skript
-- ==========================================================

-- 1. Jadvalni yaratish
CREATE TABLE IF NOT EXISTS animes (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(255) UNIQUE NOT NULL,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(100) DEFAULT 'yangi',
  views_count INTEGER DEFAULT 0,
  rating NUMERIC(3, 1) DEFAULT 8.0,
  data JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Qidiruv va saralash indexlari
CREATE INDEX IF NOT EXISTS idx_animes_category ON animes(category);
CREATE INDEX IF NOT EXISTS idx_animes_rating ON animes(rating DESC);
CREATE INDEX IF NOT EXISTS idx_animes_views ON animes(views_count DESC);
CREATE INDEX IF NOT EXISTS idx_animes_data_gin ON animes USING gin (data);

-- 3. Barcha 26 ta anime ma'lumotlarini yuklash (JSONB)
INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (1, 'juda-ham-yoqimtoy-mabuda-ova', 'Juda ham yoqimtoy ma''buda (OVA)', 'yangi', 24500, 8.7, '{"id":1,"slug":"juda-ham-yoqimtoy-mabuda-ova","title":"Juda ham yoqimtoy ma''buda (OVA)","original_title":"Kamisama Hajimemashita: Kako-hen","russian_title":"Очень приятно, Бог: Прошлое","description":"Nanami Tomoening o''tmishidagi sirli lanatni bartaraf etish va uning hayotini qutqarish uchun vaqt bo''ylab o''tmishga sayohat qiladi. Tomoening haqiqiy sevgisi va Yuko xonim siri ochiladi.","poster_url":"https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80","type":"OVA (Maxsus)","episodes":"4 / 4","current_episode":4,"total_episodes":4,"year":2015,"views_count":24500,"rating":8.7,"status":"Tugallangan","duration":"30 daq.","age_rating":"13+","genres":["Romantika","Fantaziya","G''ayritabiiy","Shojo"],"sub_available":true,"dub_available":true,"category":"yangi","telegram_code":"anime_kamisama_ova","metadata":{"studio":"TMS Entertainment","director":"Akitaro Daichi","language":"O''zbekcha Ovozli & Subtitr"}}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (2, 'juda-ham-yoqimtoy-mabuda-2-fasl', 'Juda ham yoqimtoy ma''buda 2-fasl', 'yangi', 31200, 8.5, '{"id":2,"slug":"juda-ham-yoqimtoy-mabuda-2-fasl","title":"Juda ham yoqimtoy ma''buda 2-fasl","original_title":"Kamisama Hajimemashita ◎","russian_title":"Очень приятно, Бог 2","description":"Nanami Momozo ibodatxona xudosi sifatidagi mahoratini oshirib boradi. Izumo ilohiy yig''ilishi va Kurama tog''idagi qarg''a-tengu qabilasi bilan bo''lgan yangi sarguzashtlar.","poster_url":"https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80","type":"TV serial","episodes":"12 / 12","current_episode":12,"total_episodes":12,"year":2015,"views_count":31200,"rating":8.5,"status":"Tugallangan","duration":"24 daq.","age_rating":"13+","genres":["Komediya","Romantika","Fantaziya","Shojo"],"sub_available":true,"dub_available":true,"category":"yangi","telegram_code":"anime_kamisama_s2","metadata":{"studio":"TMS Entertainment"}}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (3, 'vayolet-evergarden-film', 'Vayolet Evergarden', 'yangi', 58000, 9.1, '{"id":3,"slug":"vayolet-evergarden-film","title":"Vayolet Evergarden","original_title":"Violet Evergarden: The Movie","russian_title":"Вайолет Эвергарден. Фильм","description":"Urushdan so''ng his-tuyg''ular ma''nosini anglashga uringan Vayoletning mayor Gilbertga bo''lgan cheksiz sevgisi va so''nggi ta''sirli maktubi.","poster_url":"https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80","type":"Film","episodes":"1 / 1","current_episode":1,"total_episodes":1,"year":2020,"views_count":58000,"rating":9.1,"status":"Tugallangan","duration":"140 daq.","age_rating":"16+","genres":["Drama","Fantaziya","Romantika"],"sub_available":true,"dub_available":true,"category":"yangi","telegram_code":"anime_violet_movie","metadata":{"studio":"Kyoto Animation"}}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (4, 'dorohedoro-maxsus', 'Dorohedoro', 'yangi', 19800, 8.2, '{"id":4,"slug":"dorohedoro-maxsus","title":"Dorohedoro","original_title":"Dorohedoro: Ma no Omake","russian_title":"Дорохедоро OVA","description":"Timsallashgan Kaiman va Nikaidoning g''ayritabiiy sehrgarlar olamidagi la''natni qidirish sarguzashtlari haqidagi maxsus epizodlar.","poster_url":"https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80","type":"OVA (Maxsus)","episodes":"6 / 6","current_episode":6,"total_episodes":6,"year":2020,"views_count":19800,"rating":8.2,"status":"Tugallangan","duration":"5 daq.","age_rating":"18+","genres":["Ekshn","Komediya","G''ayritabiiy"],"sub_available":true,"dub_available":true,"category":"yangi","telegram_code":"anime_dorohedoro_ova","metadata":{"studio":"MAPPA"}}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (5, 'solo-leveling-2', 'Yolg''iz Daraja Ko''tarish 2', 'songgi', 145000, 9.3, '{"id":5,"slug":"solo-leveling-2","title":"Yolg''iz Daraja Ko''tarish 2","original_title":"Ore dake Level Up na Ken Season 2","russian_title":"Поднятие уровня в одиночку 2","description":"Sung Jin-woo o''zining soya armiyasi bilan yangi S-darajali darvozalarga qarshi chiqadi. Dunyo xavf ostida!","poster_url":"https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80","type":"TV serial","episodes":"9 / 13","current_episode":9,"total_episodes":13,"year":2025,"views_count":145000,"rating":9.3,"status":"Davom etmoqda","duration":"24 daq.","age_rating":"16+","genres":["Ekshn","Fantaziya","Sarguzasht"],"sub_available":true,"dub_available":true,"category":"songgi","telegram_code":"anime_solo_leveling_s2","update_time":"19:45"} '::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (6, 'demon-slayer-infinity-castle', 'Iblislar Qotili: Cheksiz Qasr', 'songgi', 210000, 9.5, '{"id":6,"slug":"demon-slayer-infinity-castle","title":"Iblislar Qotili: Cheksiz Qasr","original_title":"Kimetsu no Yaiba: Mugen Jou-hen","russian_title":"Клинок, рассекающий демонов: Бесконечная крепость","description":"Muzan Kibutsuji va yuqori darajali iblislarga qarshi barcha Hashiralar va Tanjironing hal qiluvchi jangi.","poster_url":"https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=600&auto=format&fit=crop&q=80","type":"Film","episodes":"1 / 3","current_episode":1,"total_episodes":3,"year":2025,"views_count":210000,"rating":9.5,"status":"Tez kunda","duration":"115 daq.","age_rating":"16+","genres":["Ekshn","Fantaziya","Tarixiy"],"sub_available":true,"dub_available":true,"category":"songgi","telegram_code":"anime_demon_slayer_castle","update_time":"20:30"} '::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (7, 'shingeki-no-kyojin-final', 'Titanlar Hujumi: Yakuniy Qism', 'birinchilardan', 340000, 9.6, '{"id":7,"slug":"shingeki-no-kyojin-final","title":"Titanlar Hujumi: Yakuniy Qism","original_title":"Shingeki no Kyojin: The Final Season","russian_title":"Атака титанов: Финал","description":"Eren Yeger dunyoni yo''q qilishni boshlaganida, uning eski do''stlari uni to''xtatish uchun birlashadilar.","poster_url":"https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80","type":"TV serial","episodes":"28 / 28","current_episode":28,"total_episodes":28,"year":2023,"views_count":340000,"rating":9.6,"status":"Tugallangan","duration":"25 daq.","age_rating":"18+","genres":["Ekshn","Drama","Fantaziya","Misteriya"],"sub_available":true,"dub_available":true,"category":"birinchilardan","telegram_code":"anime_aot_final"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (8, 'jujutsu-kaisen-s2', 'Sehrli Jang 2-fasl: Shibuya', 'birinchilardan', 290000, 9.4, '{"id":8,"slug":"jujutsu-kaisen-s2","title":"Sehrli Jang 2-fasl: Shibuya","original_title":"Jujutsu Kaisen 2nd Season","russian_title":"Магическая битва 2","description":"Shibuya stansiyasida Gotjo Satoruni muhrlash rejasi va maxsus darajadagi la''natlarning qonli to''qnashuvi.","poster_url":"https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80","type":"TV serial","episodes":"23 / 23","current_episode":23,"total_episodes":23,"year":2023,"views_count":290000,"rating":9.4,"status":"Tugallangan","duration":"24 daq.","age_rating":"16+","genres":["Ekshn","Fantaziya","G''ayritabiiy"],"sub_available":true,"dub_available":true,"category":"birinchilardan","telegram_code":"anime_jjk_s2"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (9, 'bleach-thousand-year-blood-war', 'Bleach: Ming Yillik Qonli Urush', 'birinchilardan', 180000, 9.2, '{"id":9,"slug":"bleach-thousand-year-blood-war","title":"Bleach: Ming Yillik Qonli Urush","original_title":"Bleach: Sennen Kessen-hen","russian_title":"Блич: Тысячелетняя кровавая война","description":"Kvinsilar qiroli Yhwach Soul Societyga hujum qiladi. Ichigo o''zining haqiqiy kuchini kashf etadi.","poster_url":"https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80","type":"TV serial","episodes":"26 / 52","current_episode":26,"total_episodes":52,"year":2024,"views_count":180000,"rating":9.2,"status":"Davom etmoqda","duration":"24 daq.","age_rating":"16+","genres":["Ekshn","Sarguzasht","G''ayritabiiy"],"sub_available":true,"dub_available":true,"category":"birinchilardan","telegram_code":"anime_bleach_tybw"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (10, 'frieren-beyond-journeys-end', 'Frieren: Sayohat Yakunidan So''ng', 'birinchilardan', 220000, 9.5, '{"id":10,"slug":"frieren-beyond-journeys-end","title":"Frieren: Sayohat Yakunidan So''ng","original_title":"Sousou no Frieren","russian_title":"Провожающая в последний путь Фрирен","description":"Qahramonlar guruhi yovuz iblislar qirolini mag''lub etgandan so''ng, o''lmas elf sehrgar qiz insoniy his-tuyg''ularni tushunish uchun sayohatga chiqadi.","poster_url":"https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80","type":"TV serial","episodes":"28 / 28","current_episode":28,"total_episodes":28,"year":2024,"views_count":220000,"rating":9.5,"status":"Tugallangan","duration":"24 daq.","age_rating":"13+","genres":["Sarguzasht","Drama","Fantaziya"],"sub_available":true,"dub_available":true,"category":"birinchilardan","telegram_code":"anime_frieren"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (11, 'one-piece-egghead', 'One Piece: Egghead Oroli', 'bugungi_top', 450000, 9.2, '{"id":11,"slug":"one-piece-egghead","title":"One Piece: Egghead Oroli","original_title":"One Piece: Egghead Arc","russian_title":"Ван Пис: Остров Яйцеголового","description":"Luffy va uning jamoasi kelajak oroli bo''lmish Eggheadga yetib kelishadi va buyuk olim Vegapunk bilan uchrashadilar.","poster_url":"https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80","type":"TV serial","episodes":"1120 / 1200","current_episode":1120,"total_episodes":1200,"year":2024,"views_count":450000,"rating":9.2,"status":"Davom etmoqda","duration":"24 daq.","age_rating":"13+","genres":["Ekshn","Sarguzasht","Komediya","Fantaziya"],"sub_available":true,"dub_available":true,"category":"bugungi_top","telegram_code":"anime_one_piece"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (12, 'chainsaw-man-movie', 'Benzopila Odam: Reze Kamoni', 'bugungi_top', 165000, 9.0, '{"id":12,"slug":"chainsaw-man-movie","title":"Benzopila Odam: Reze Kamoni","original_title":"Chainsaw Man: Reze-hen","russian_title":"Человек-бензопила: Арка Резе","description":"Denji sirli va maftunkor qiz Reze bilan uchrashadi. Ammo uning asl shaxsi Denji hayotini xavf ostiga qo''yadi.","poster_url":"https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80","type":"Film","episodes":"1 / 1","current_episode":1,"total_episodes":1,"year":2025,"views_count":165000,"rating":9.0,"status":"Kutilmoqda","duration":"95 daq.","age_rating":"18+","genres":["Ekshn","G''ayritabiiy","Romantika"],"sub_available":true,"dub_available":true,"category":"bugungi_top","telegram_code":"anime_chainsaw_reze"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (13, 'wind-breaker', 'Shamol To''xtatuvchi', 'bugungi_top', 95000, 8.6, '{"id":13,"slug":"wind-breaker","title":"Shamol To''xtatuvchi","original_title":"Wind Breaker","russian_title":"Ветролом","description":"Haruka Sakura faqat kuchli raqiblar bilan kurashishni xohlaydigan o''spirin, Furin maktabiga o''zini ko''rsatish uchun keladi.","poster_url":"https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80","type":"TV serial","episodes":"13 / 13","current_episode":13,"total_episodes":13,"year":2024,"views_count":95000,"rating":8.6,"status":"Tugallangan","duration":"24 daq.","age_rating":"16+","genres":["Ekshn","Maktab","Drama"],"sub_available":true,"dub_available":true,"category":"bugungi_top","telegram_code":"anime_wind_breaker"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (14, 'naruto-shippuden-hd', 'Naruto: Dovulli Yillar (HD)', 'bugungi_top', 890000, 9.4, '{"id":14,"slug":"naruto-shippuden-hd","title":"Naruto: Dovulli Yillar (HD)","original_title":"Naruto: Shippuuden","russian_title":"Наруто: Ураганные хроники","description":"Naruto Uzumaki 2.5 yillik mashg''ulotlardan so''ng qishloqqa qaytadi va Akatsuki tashkilotiga qarshi kurashadi.","poster_url":"https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80","type":"TV serial","episodes":"500 / 500","current_episode":500,"total_episodes":500,"year":2017,"views_count":890000,"rating":9.4,"status":"Tugallangan","duration":"23 daq.","age_rating":"13+","genres":["Ekshn","Sarguzasht","Jang san''ati"],"sub_available":true,"dub_available":true,"category":"bugungi_top","telegram_code":"anime_naruto_shippuden"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (15, 'death-note', 'O''lim Daftari', 'oylik_top', 670000, 9.5, '{"id":15,"slug":"death-note","title":"O''lim Daftari","original_title":"Death Note","russian_title":"Тетрадь смерти","description":"Yagami Light sirli daftarga egalik qilib oladi. Bu daftar orqali yozilgan har qanday odam o''ladi. Detektiv L uni qidirishga kirishadi.","poster_url":"https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80","type":"TV serial","episodes":"37 / 37","current_episode":37,"total_episodes":37,"year":2007,"views_count":670000,"rating":9.5,"status":"Tugallangan","duration":"23 daq.","age_rating":"16+","genres":["Detektiv","Psixologik","G''ayritabiiy"],"sub_available":true,"dub_available":true,"category":"oylik_top","telegram_code":"anime_death_note"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (16, 'fullmetal-alchemist-brotherhood', 'Po''lat Alximik: Birodarlik', 'oylik_top', 520000, 9.7, '{"id":16,"slug":"fullmetal-alchemist-brotherhood","title":"Po''lat Alximik: Birodarlik","original_title":"Fullmetal Alchemist: Brotherhood","russian_title":"Стальной алхимик: Братство","description":"Edvard va Alfons Elrik onalarini tiriltirishga urinib yo''qotgan tanalarini qaytarish uchun Falsafa toshini qidirishadi.","poster_url":"https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80","type":"TV serial","episodes":"64 / 64","current_episode":64,"total_episodes":64,"year":2010,"views_count":520000,"rating":9.7,"status":"Tugallangan","duration":"24 daq.","age_rating":"16+","genres":["Ekshn","Sarguzasht","Drama","Fantaziya"],"sub_available":true,"dub_available":true,"category":"oylik_top","telegram_code":"anime_fmab"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (17, 'hunter-x-hunter', 'Hunter x Hunter', 'oylik_top', 430000, 9.4, '{"id":17,"slug":"hunter-x-hunter","title":"Hunter x Hunter","original_title":"Hunter x Hunter (2011)","russian_title":"Хантер х Хантер","description":"Gon Freecss otasini topish va afsonaviy ovchiga aylanish uchun Hunter imtihonidan o''tadi va yangi do''stlar orttiradi.","poster_url":"https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80","type":"TV serial","episodes":"148 / 148","current_episode":148,"total_episodes":148,"year":2014,"views_count":430000,"rating":9.4,"status":"Tugallangan","duration":"23 daq.","age_rating":"13+","genres":["Ekshn","Sarguzasht","Fantaziya"],"sub_available":true,"dub_available":true,"category":"oylik_top","telegram_code":"anime_hxh"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (18, 'code-geass', 'Kod Giass: Qo''zg''olonchi Lelush', 'oylik_top', 380000, 9.3, '{"id":18,"slug":"code-geass","title":"Kod Giass: Qo''zg''olonchi Lelush","original_title":"Code Geass: Hangyaku no Lelouch","russian_title":"Код Гиас: Восставший Лелуш","description":"Shahzoda Lelush mutlaq itoat ettirish qudrati bo''lgan Giass kuchiga ega bo''ladi va Britaniya imperiyasiga qarshi urush e''lon qiladi.","poster_url":"https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80","type":"TV serial","episodes":"50 / 50","current_episode":50,"total_episodes":50,"year":2008,"views_count":380000,"rating":9.3,"status":"Tugallangan","duration":"24 daq.","age_rating":"16+","genres":["Ekshn","Meha","Harbiy","Psixologik"],"sub_available":true,"dub_available":true,"category":"oylik_top","telegram_code":"anime_code_geass"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (19, 'your-name', 'Sening Isming (Kimi no Na wa)', 'filmlar', 540000, 9.4, '{"id":19,"slug":"your-name","title":"Sening Isming (Kimi no Na wa)","original_title":"Kimi no Na wa.","russian_title":"Твоё имя","description":"Tokioda yashovchi Taki va qishloqlik Mitsuha tushlarida tanalari almashib qolayotganini tushunishadi.","poster_url":"https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80","type":"Film","episodes":"1 / 1","current_episode":1,"total_episodes":1,"year":2016,"views_count":540000,"rating":9.4,"status":"Tugallangan","duration":"106 daq.","age_rating":"12+","genres":["Drama","Romantika","G''ayritabiiy"],"sub_available":true,"dub_available":true,"category":"filmlar","telegram_code":"anime_your_name"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (20, 'suzume', 'Suzume Eshiklarni Yopmoqda', 'filmlar', 310000, 8.9, '{"id":20,"slug":"suzume","title":"Suzume Eshiklarni Yopmoqda","original_title":"Suzume no Tojimari","russian_title":"Судзумэ, закрывающая двери","description":"17 yoshli Suzume butun Yaponiya bo''ylab ofatlarni chaqiruvchi sirli eshiklarni yopish uchun sehrli sayohatga otlanadi.","poster_url":"https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80","type":"Film","episodes":"1 / 1","current_episode":1,"total_episodes":1,"year":2022,"views_count":310000,"rating":8.9,"status":"Tugallangan","duration":"122 daq.","age_rating":"12+","genres":["Sarguzasht","Fantaziya"],"sub_available":true,"dub_available":true,"category":"filmlar","telegram_code":"anime_suzume"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (21, 'spirited-away', 'Ruhlar Qamrovida (Hayao Miyazaki)', 'filmlar', 610000, 9.6, '{"id":21,"slug":"spirited-away","title":"Ruhlar Qamrovida (Hayao Miyazaki)","original_title":"Sen to Chihiro no Kamikakushi","russian_title":"Унесённые призраками","description":"Kichik Chihiro sehrli ruhlar olamiga tushib qoladi va cho''chqaga aylangan ota-onasini qutqarish uchun Yubaba vannaxonasida ishlaydi.","poster_url":"https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=600&auto=format&fit=crop&q=80","type":"Film","episodes":"1 / 1","current_episode":1,"total_episodes":1,"year":2001,"views_count":610000,"rating":9.6,"status":"Tugallangan","duration":"125 daq.","age_rating":"6+","genres":["Sarguzasht","Fantaziya","Oila"],"sub_available":true,"dub_available":true,"category":"filmlar","telegram_code":"anime_spirited_away"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (22, 'howls-moving-castle', 'Xaullning Yuruvchi Qasri', 'filmlar', 490000, 9.3, '{"id":22,"slug":"howls-moving-castle","title":"Xaullning Yuruvchi Qasri","original_title":"Howl no Ugoku Shiro","russian_title":"Ходячий замок","description":"Yovuz jodugar tomonidan kampirga aylantirilgan Sofi yosh va sirli sehrgar Xaullning yuruvchi ulkan qasriga panoh topadi.","poster_url":"https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80","type":"Film","episodes":"1 / 1","current_episode":1,"total_episodes":1,"year":2004,"views_count":490000,"rating":9.3,"status":"Tugallangan","duration":"119 daq.","age_rating":"12+","genres":["Sarguzasht","Fantaziya","Romantika"],"sub_available":true,"dub_available":true,"category":"filmlar","telegram_code":"anime_howl_castle"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (23, 'steins-gate', 'Shtayn Darvozasi (Steins;Gate)', 'tasodifiy', 360000, 9.4, '{"id":23,"slug":"steins-gate","title":"Shtayn Darvozasi (Steins;Gate)","original_title":"Steins;Gate","russian_title":"Врата Штейна","description":"O''zini telba olim deb hisoblovchi Okabe Rintaro mikroto''lqinli pech yordamida o''tmishga xabar yuborish yo''lini topadi.","poster_url":"https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80","type":"TV serial","episodes":"24 / 24","current_episode":24,"total_episodes":24,"year":2011,"views_count":360000,"rating":9.4,"status":"Tugallangan","duration":"24 daq.","age_rating":"16+","genres":["Ilmiy fantastika","Triller","Psixologik"],"sub_available":true,"dub_available":true,"category":"tasodifiy","telegram_code":"anime_steins_gate"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (24, 'tokyo-ghoul', 'Tokio Ghuli (Tokyo Ghoul)', 'tasodifiy', 510000, 8.8, '{"id":24,"slug":"tokyo-ghoul","title":"Tokio Ghuli (Tokyo Ghoul)","original_title":"Tokyo Ghoul","russian_title":"Токийский гуль","description":"Ken Kaneki xavfli uchrashuvdan so''ng yarim-inson, yarim-ghulga aylanadi va ikki dunyo o''rtasida omon qolishga harakat qiladi.","poster_url":"https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80","type":"TV serial","episodes":"12 / 12","current_episode":12,"total_episodes":12,"year":2014,"views_count":510000,"rating":8.8,"status":"Tugallangan","duration":"24 daq.","age_rating":"18+","genres":["Ekshn","Triller","G''ayritabiiy","Dahshat"],"sub_available":true,"dub_available":true,"category":"tasodifiy","telegram_code":"anime_tokyo_ghoul"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (25, 'erased', 'Shahardan Yo''qolganimda (Erased)', 'tasodifiy', 270000, 8.9, '{"id":25,"slug":"erased","title":"Shahardan Yo''qolganimda (Erased)","original_title":"Boku dake ga Inai Machi","russian_title":"Город, в котором меня нет","description":"Satoru Fujinuma fojialarning oldini olish uchun o''tmishga sakrash qobiliyatiga ega. U onasini qutqarish uchun 18 yil orqaga qaytadi.","poster_url":"https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80","type":"TV serial","episodes":"12 / 12","current_episode":12,"total_episodes":12,"year":2016,"views_count":270000,"rating":8.9,"status":"Tugallangan","duration":"23 daq.","age_rating":"16+","genres":["Misteriya","Psixologik","G''ayritabiiy"],"sub_available":true,"dub_available":true,"category":"tasodifiy","telegram_code":"anime_erased"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

INSERT INTO animes (id, slug, title, category, views_count, rating, data)
VALUES (26, 'mob-psycho-100', 'Mob Psixo 100', 'tasodifiy', 310000, 9.1, '{"id":26,"slug":"mob-psycho-100","title":"Mob Psixo 100","original_title":"Mob Psycho 100","russian_title":"Моб Психо 100","description":"Shigeo Kageyama (Mob) ulkan ruhiy qudratga ega 8-sinf o''quvchisi. U oddiy hayot kechirishni istaydi, lekin uning his-tuyg''ulari 100% ga yetganda qudrati portlaydi.","poster_url":"https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80","type":"TV serial","episodes":"12 / 12","current_episode":12,"total_episodes":12,"year":2016,"views_count":310000,"rating":9.1,"status":"Tugallangan","duration":"24 daq.","age_rating":"13+","genres":["Ekshn","Komediya","G''ayritabiiy"],"sub_available":true,"dub_available":true,"category":"tasodifiy","telegram_code":"anime_mob_psycho"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, views_count = EXCLUDED.views_count, rating = EXCLUDED.rating, data = EXCLUDED.data;

-- Serial sekvensiyani yangilash
SELECT setval('animes_id_seq', (SELECT COALESCE(MAX(id), 1) FROM animes));
