export interface AnimeItem {
  id: number;
  slug: string;
  title: string;
  original_title: string;
  russian_title?: string;
  description: string;
  poster_url: string;
  banner_url?: string;
  type: 'TV serial' | 'Film' | 'OVA (Maxsus)';
  episodes: string;
  current_episode: number;
  total_episodes: number;
  year: number;
  views_count: number;
  rating: number;
  status: string;
  duration: string;
  age_rating: string;
  genres: string[];
  sub_available: boolean;
  dub_available: boolean;
  category: 'yangi' | 'songgi' | 'birinchilardan' | 'bugungi_top' | 'oylik_top' | 'filmlar' | 'tasodifiy';
  telegram_code: string;
  update_time?: string;
  metadata?: Record<string, any>;
}

export const initialAnimes: AnimeItem[] = [
  // --- YANGI ANIMELAR ---
  {
    id: 1,
    slug: "juda-ham-yoqimtoy-mabuda-ova",
    title: "Juda ham yoqimtoy ma'buda (OVA)",
    original_title: "Kamisama Hajimemashita: Kako-hen",
    russian_title: "Очень приятно, Бог: Прошлое",
    description: "Nanami Tomoening o'tmishidagi sirli lanatni bartaraf etish va uning hayotini qutqarish uchun vaqt bo'ylab o'tmishga sayohat qiladi. Tomoening haqiqiy sevgisi va Yuko xonim siri ochiladi.",
    poster_url: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80",
    type: "OVA (Maxsus)",
    episodes: "4 / 4",
    current_episode: 4,
    total_episodes: 4,
    year: 2015,
    views_count: 24500,
    rating: 8.7,
    status: "Tugallangan",
    duration: "30 daq.",
    age_rating: "13+",
    genres: ["Romantika", "Fantaziya", "G'ayritabiiy", "Shojo"],
    sub_available: true,
    dub_available: true,
    category: "yangi",
    telegram_code: "anime_kamisama_ova",
    metadata: {
      studio: "TMS Entertainment",
      director: "Akitaro Daichi",
      language: "O'zbekcha Ovozli & Subtitr"
    }
  },
  {
    id: 2,
    slug: "juda-ham-yoqimtoy-mabuda-2-fasl",
    title: "Juda ham yoqimtoy ma'buda 2-fasl",
    original_title: "Kamisama Hajimemashita ◎",
    russian_title: "Очень приятно, Бог 2",
    description: "Nanami Momozo ibodatxona xudosi sifatidagi mahoratini oshirib boradi. Izumo ilohiy yig'ilishi va Kurama tog'idagi qarg'a-tengu qabilasi bilan bo'lgan yangi sarguzashtlar.",
    poster_url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80",
    type: "TV serial",
    episodes: "12 / 12",
    current_episode: 12,
    total_episodes: 12,
    year: 2015,
    views_count: 31200,
    rating: 8.5,
    status: "Tugallangan",
    duration: "24 daq.",
    age_rating: "13+",
    genres: ["Komediya", "Romantika", "Fantaziya", "Shojo"],
    sub_available: true,
    dub_available: true,
    category: "yangi",
    telegram_code: "anime_kamisama_s2",
    metadata: { studio: "TMS Entertainment" }
  },
  {
    id: 3,
    slug: "vayolet-evergarden-film",
    title: "Vayolet Evergarden",
    original_title: "Violet Evergarden: The Movie",
    russian_title: "Вайолет Эвергарден. Фильм",
    description: "Urushdan so'ng his-tuyg'ular ma'nosini anglashga uringan Vayoletning mayor Gilbertga bo'lgan cheksiz sevgisi va so'nggi ta'sirli maktubi.",
    poster_url: "https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80",
    type: "Film",
    episodes: "1 / 1",
    current_episode: 1,
    total_episodes: 1,
    year: 2020,
    views_count: 58000,
    rating: 9.1,
    status: "Tugallangan",
    duration: "2 soat 20 daq.",
    age_rating: "13+",
    genres: ["Drama", "Fantaziya", "Romantika", "Hayotiy"],
    sub_available: true,
    dub_available: true,
    category: "yangi",
    telegram_code: "anime_violet_movie",
    metadata: { studio: "Kyoto Animation", is_sub: true }
  },
  {
    id: 4,
    slug: "elektr-asri-kashfiyotlar-tarixi",
    title: "Elektr asri kashfiyotlar tarixi",
    original_title: "20 Seiki Denki Mokuroku",
    russian_title: "Двадцатый век: Каталог электричества",
    description: "1907-yil Kioto shahrida texnologiya, elektr nurlari va sevgi orqali kelajakka yo'l ochayotgan ikki yosh qahramon qissasi.",
    poster_url: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80",
    type: "TV serial",
    episodes: "12 / 12",
    current_episode: 12,
    total_episodes: 12,
    year: 2021,
    views_count: 14200,
    rating: 8.0,
    status: "Tugallangan",
    duration: "24 daq.",
    age_rating: "12+",
    genres: ["Tarixiy", "Sarguzasht", "Romantika"],
    sub_available: true,
    dub_available: false,
    category: "yangi",
    telegram_code: "anime_elektr_asri",
    metadata: { studio: "Kyoto Animation" }
  },

  // --- SO'NGGI YANGILANISHLAR ---
  {
    id: 5,
    slug: "rezero-hayotni-noldan-boshlash-4-fasl",
    title: "ReZero: Hayotni noldan boshlash 4 – ...",
    original_title: "Re:Zero kara Hajimeru Isekai Seikatsu 4th Season",
    russian_title: "Re:Zero. Жизнь с нуля в другом мире 4",
    description: "Subaru Natsuki o'limdan qaytish qobiliyati orqali o'z do'stlarini qutqarishda davom etadi. Qattiq janglar va yangi arxiyepiskoplar tahdidi boshlanadi.",
    poster_url: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    type: "TV serial",
    episodes: "8 / 16",
    current_episode: 8,
    total_episodes: 16,
    year: 2024,
    views_count: 82000,
    rating: 8.9,
    status: "Davom etmoqda",
    duration: "24 daq.",
    age_rating: "18+",
    genres: ["Psixologik", "Drama", "Fantaziya", "Isekai", "Triller"],
    sub_available: true,
    dub_available: true,
    category: "songgi",
    telegram_code: "anime_rezero_s4",
    update_time: "2 kun avval",
    metadata: { new_episode: "+ 1 epizod", studio: "White Fox" }
  },
  {
    id: 6,
    slug: "dunyo-raqsga-tushganda",
    title: "Dunyo raqsga tushganda",
    original_title: "Sekai ga Odoru Toki",
    russian_title: "Когда мир танцует",
    description: "Musiqa, tuyg'ular va raqs sahnasidagi qizg'in intilishlar yoshlarni yangi darajaga yetaklaydi.",
    poster_url: "https://images.unsplash.com/photo-1516331138075-f3adc1e149cd?w=600&auto=format&fit=crop&q=80",
    type: "TV serial",
    episodes: "6 / 12",
    current_episode: 6,
    total_episodes: 12,
    year: 2024,
    views_count: 19400,
    rating: 7.8,
    status: "Davom etmoqda",
    duration: "23 daq.",
    age_rating: "13+",
    genres: ["Musiqa", "Drama", "Maktab"],
    sub_available: true,
    dub_available: false,
    category: "songgi",
    telegram_code: "anime_dunyo_raqs",
    update_time: "2 kun avval",
    metadata: { new_episode: "+ 1 epizod", studio: "CloverWorks" }
  },

  // --- BIRINCHILARDAN BO'LING ---
  {
    id: 7,
    slug: "senyuu-2",
    title: "Senyuu. 2",
    original_title: "Senyuu. 2",
    russian_title: "Сэнъю 2",
    description: "Qahramon Alba va sadistik askar Ross iblislar qiroli Ruki bilan birgalikda kulgili va kutilmagan sarguzashtlarga duch keladilar.",
    poster_url: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80",
    type: "TV serial",
    episodes: "13 / 13",
    current_episode: 13,
    total_episodes: 13,
    year: 2013,
    views_count: 16500,
    rating: 7.7,
    status: "Tugallangan",
    duration: "5 daq.",
    age_rating: "13+",
    genres: ["Komediya", "Parodiya", "Fantaziya", "Shounen"],
    sub_available: true,
    dub_available: true,
    category: "birinchilardan",
    telegram_code: "anime_senyuu_2",
    metadata: { studio: "LIDENFILMS" }
  },
  {
    id: 8,
    slug: "ziyofatchi-kunmin",
    title: "Ziyofatchi Kunmin",
    original_title: "Paripi Koumei",
    russian_title: "Тусовщик Кунмин",
    description: "Qadimgi Xitoy sarkardasi Juge Lyan zamonaviy Tokioning Shibuya klublariga tushib qolib, iqtidorli qo'shiqchi Eiko Tsukimining prodyuseriga aylanadi.",
    poster_url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80",
    type: "TV serial",
    episodes: "12 / 12",
    current_episode: 12,
    total_episodes: 12,
    year: 2022,
    views_count: 38900,
    rating: 8.3,
    status: "Tugallangan",
    duration: "24 daq.",
    age_rating: "13+",
    genres: ["Komediya", "Musiqa", "G'ayritabiiy"],
    sub_available: true,
    dub_available: true,
    category: "birinchilardan",
    telegram_code: "anime_paripi_koumei",
    metadata: { studio: "P.A. Works" }
  },
  {
    id: 9,
    slug: "vayolet-evergarden-film-2",
    title: "Vayolet Evergar...",
    original_title: "Violet Evergarden: Eternity and the Auto Memory Doll",
    russian_title: "Вайолет Эвергарден: Вечность и призрак пера",
    description: "Izabella York qizlar internatida Vayoletdan odob-axloq o'rganadi. Ikkisi o'rtasidagi do'stlik maktublar orqali abadiy saqlanadi.",
    poster_url: "https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80",
    type: "Film",
    episodes: "1 / 1",
    current_episode: 1,
    total_episodes: 1,
    year: 2019,
    views_count: 42000,
    rating: 8.6,
    status: "Tugallangan",
    duration: "1 soat 30 daq.",
    age_rating: "13+",
    genres: ["Drama", "Fantaziya", "Hayotiy"],
    sub_available: true,
    dub_available: true,
    category: "birinchilardan",
    telegram_code: "anime_violet_gaiden",
    metadata: { studio: "Kyoto Animation", is_sub: true }
  },
  {
    id: 10,
    slug: "mingyillik-aktrisasi",
    title: "Mingyillik Aktrisasi",
    original_title: "Millennium Actress (Sennen Joyuu)",
    russian_title: "Актриса тысячелетия",
    description: "Satoshi Konning afsonaviy asari. Faxriy aktrisa Chiyoko o'zining sirli sevgilisi izidan butun Yaponiya tarixi bo'ylab kinolarda yashagan umrini xotirlaydi.",
    poster_url: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80",
    type: "Film",
    episodes: "1 / 1",
    current_episode: 1,
    total_episodes: 1,
    year: 2001,
    views_count: 28400,
    rating: 8.5,
    status: "Tugallangan",
    duration: "1 soat 27 daq.",
    age_rating: "12+",
    genres: ["Drama", "Tarixiy", "Romantika", "Psixologik"],
    sub_available: true,
    dub_available: false,
    category: "birinchilardan",
    telegram_code: "anime_sennen_joyuu",
    metadata: { studio: "Madhouse", is_sub: true }
  },

  // --- BUGUNGI TOP ---
  {
    id: 11,
    slug: "naruto-boron-yillari-top",
    title: "Naruto: Bo'ron yi...",
    original_title: "Naruto: Shippuuden",
    russian_title: "Наруто: Ураганные хроники",
    description: "Naruto Uzumaki do'sti Sasuskeni qaytarish va Shinobi olamini qutqarish uchun barcha kuchini sarflaydi.",
    poster_url: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80",
    type: "TV serial",
    episodes: "500 / 500",
    current_episode: 500,
    total_episodes: 500,
    year: 2007,
    views_count: 245000,
    rating: 9.3,
    status: "Tugallangan",
    duration: "23 daq.",
    age_rating: "13+",
    genres: ["Jangari", "Sarguzasht", "Shounen", "Ninja"],
    sub_available: true,
    dub_available: true,
    category: "bugungi_top",
    telegram_code: "anime_naruto_shippuuden",
    metadata: { studio: "Pierrot" }
  },
  {
    id: 12,
    slug: "qora-klever-top",
    title: "Qora Klever",
    original_title: "Black Clover",
    russian_title: "Черный клевер",
    description: "Sehr bo'lmagan Asta besh bargli kitob bilan Sehrgarlar Qiroli bo'lishga qadam tashlaydi.",
    poster_url: "https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80",
    type: "TV serial",
    episodes: "170 / 170",
    current_episode: 170,
    total_episodes: 170,
    year: 2017,
    views_count: 168000,
    rating: 8.6,
    status: "Tugallangan",
    duration: "24 daq.",
    age_rating: "13+",
    genres: ["Jangari", "Sehr-jodu", "Shounen"],
    sub_available: true,
    dub_available: true,
    category: "bugungi_top",
    telegram_code: "anime_black_clover",
    metadata: { studio: "Pierrot" }
  },
  {
    id: 13,
    slug: "naruto-top",
    title: "Naruto",
    original_title: "Naruto (Season 1)",
    russian_title: "Наруто",
    description: "Yetim Narutoning Hokage bo'lish orzusi va 7-jamoa bilan boshlagan unutilmas ilk qadamlari.",
    poster_url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80",
    type: "TV serial",
    episodes: "220 / 220",
    current_episode: 220,
    total_episodes: 220,
    year: 2002,
    views_count: 198000,
    rating: 9.0,
    status: "Tugallangan",
    duration: "23 daq.",
    age_rating: "12+",
    genres: ["Jangari", "Sarguzasht", "Komediya"],
    sub_available: true,
    dub_available: true,
    category: "bugungi_top",
    telegram_code: "anime_naruto_s1",
    metadata: { studio: "Pierrot" }
  },
  {
    id: 14,
    slug: "van-pis-top",
    title: "Van pis",
    original_title: "One Piece",
    russian_title: "Ван Пис",
    description: "Monkey D. Luffy va uning qaroqchilar guruhi One Piece xazinasini topish uchun ulkan dengizlarda sayohat qilmoqda.",
    poster_url: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80",
    type: "TV serial",
    episodes: "1120 / davom...",
    current_episode: 1120,
    total_episodes: 1200,
    year: 1999,
    views_count: 310000,
    rating: 9.2,
    status: "Davom etmoqda",
    duration: "24 daq.",
    age_rating: "13+",
    genres: ["Jangari", "Sarguzasht", "Komediya", "Super kuchlar"],
    sub_available: true,
    dub_available: true,
    category: "bugungi_top",
    telegram_code: "anime_one_piece",
    metadata: { studio: "Toei Animation" }
  },

  // --- OYLIK TOP ---
  {
    id: 15,
    slug: "naruto-boron-yillari-oylik",
    title: "Naruto: Bo'ron yi...",
    original_title: "Naruto: Shippuuden",
    russian_title: "Наруто: Ураганные хроники",
    description: "Uchinchi shinobi urushi va buyuk janglar.",
    poster_url: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80",
    type: "TV serial",
    episodes: "500 / 500",
    current_episode: 500,
    total_episodes: 500,
    year: 2007,
    views_count: 245000,
    rating: 9.3,
    status: "Tugallangan",
    duration: "23 daq.",
    age_rating: "13+",
    genres: ["Jangari", "Shounen"],
    sub_available: true,
    dub_available: true,
    category: "oylik_top",
    telegram_code: "anime_naruto_shippuuden",
    metadata: { studio: "Pierrot" }
  },
  {
    id: 16,
    slug: "naruto-oylik",
    title: "Naruto",
    original_title: "Naruto",
    russian_title: "Наруто (Классика)",
    description: "Klassik Naruto dostonining ilk mavsumlari.",
    poster_url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80",
    type: "TV serial",
    episodes: "220 / 220",
    current_episode: 220,
    total_episodes: 220,
    year: 2002,
    views_count: 198000,
    rating: 9.0,
    status: "Tugallangan",
    duration: "23 daq.",
    age_rating: "12+",
    genres: ["Jangari", "Komediya"],
    sub_available: true,
    dub_available: true,
    category: "oylik_top",
    telegram_code: "anime_naruto_s1",
    metadata: { studio: "Pierrot" }
  },
  {
    id: 17,
    slug: "qora-klever-oylik",
    title: "Qora Klever",
    original_title: "Black Clover",
    russian_title: "Черный клевер",
    description: "Sehrgarlar saltanatining himoyachilari.",
    poster_url: "https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80",
    type: "TV serial",
    episodes: "170 / 170",
    current_episode: 170,
    total_episodes: 170,
    year: 2017,
    views_count: 168000,
    rating: 8.6,
    status: "Tugallangan",
    duration: "24 daq.",
    age_rating: "13+",
    genres: ["Jangari", "Sehr-jodu"],
    sub_available: true,
    dub_available: true,
    category: "oylik_top",
    telegram_code: "anime_black_clover",
    metadata: { studio: "Pierrot" }
  },
  {
    id: 18,
    slug: "van-pis-oylik",
    title: "Van pis",
    original_title: "One Piece",
    russian_title: "Ван Пис",
    description: "Vano o'lkasidagi afsonaviy janglar.",
    poster_url: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80",
    type: "TV serial",
    episodes: "1120 / davom...",
    current_episode: 1120,
    total_episodes: 1200,
    year: 1999,
    views_count: 310000,
    rating: 9.2,
    status: "Davom etmoqda",
    duration: "24 daq.",
    age_rating: "13+",
    genres: ["Jangari", "Sarguzasht"],
    sub_available: true,
    dub_available: true,
    category: "oylik_top",
    telegram_code: "anime_one_piece",
    metadata: { studio: "Toei Animation" }
  },

  // --- FILMLAR ---
  {
    id: 19,
    slug: "sozlar-huddi-gazli-suvdek",
    title: "So'zlar huddi gaz...",
    original_title: "Words Bubble Up Like Soda Pop (Cider no You ni Kotoba ga Wakiagaru)",
    russian_title: "Слова пузырятся подобно газировке",
    description: "Hayku she'rlarini yozuvchi uyatchan bola Cherry va tish qolipini yashirish uchun niqob taqib yuruvchi mashhur Smile ismli qizning yozgi unutilmas sevgisi.",
    poster_url: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    type: "Film",
    episodes: "1 / 1",
    current_episode: 1,
    total_episodes: 1,
    year: 2021,
    views_count: 46000,
    rating: 7.9,
    status: "Tugallangan",
    duration: "1 soat 27 daq.",
    age_rating: "12+",
    genres: ["Romantika", "Musiqa", "Hayotiy", "Maktab"],
    sub_available: true,
    dub_available: true,
    category: "filmlar",
    telegram_code: "anime_cider_kotoba",
    metadata: { studio: "Signal.MD / Sublimation" }
  },
  {
    id: 20,
    slug: "yurar-qala",
    title: "Yurar qal'a",
    original_title: "Howl's Moving Castle (Hauru no Ugoku Shiro)",
    russian_title: "Ходячий замок",
    description: "Hayao Miyazaki shoh asari. Yovuz jodugar tomonidan kampirga aylantirib qo'yilgan Sofi sirli sehrgar Xaulning g'aroyib yurar qal'asiga borib qoladi.",
    poster_url: "https://images.unsplash.com/photo-1516331138075-f3adc1e149cd?w=600&auto=format&fit=crop&q=80",
    type: "Film",
    episodes: "1 / 1",
    current_episode: 1,
    total_episodes: 1,
    year: 2004,
    views_count: 185000,
    rating: 9.3,
    status: "Tugallangan",
    duration: "1 soat 59 daq.",
    age_rating: "Har qanday yoshdagilar uchun",
    genres: ["Sarguzasht", "Drama", "Fantaziya", "Romantika"],
    sub_available: true,
    dub_available: true,
    category: "filmlar",
    telegram_code: "anime_hauru_castle",
    metadata: { studio: "Studio Ghibli" }
  },
  {
    id: 21,
    slug: "hal",
    title: "Hal",
    original_title: "Hal (Haru)",
    russian_title: "Хал",
    description: "Samolyot halokatida sevgilisi Halni yo'qotgan Kurumini qayg'udan qutqarish uchun Hal qiyofasidagi robot (Q01) unga yordamga keladi.",
    poster_url: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80",
    type: "Film",
    episodes: "1 / 1",
    current_episode: 1,
    total_episodes: 1,
    year: 2013,
    views_count: 34000,
    rating: 7.7,
    status: "Tugallangan",
    duration: "1 soat",
    age_rating: "13+",
    genres: ["Romantika", "Ilmiy-fantastika", "Shoujo"],
    sub_available: true,
    dub_available: true,
    category: "filmlar",
    telegram_code: "anime_hal_movie",
    metadata: { studio: "Wit Studio" }
  },
  {
    id: 22,
    slug: "malika-mononoke",
    title: "Malika Mononoke",
    original_title: "Mononoke Hime",
    russian_title: "Принцесса Мононоке",
    description: "Tabiat va insoniyat texnologiyasi o'rtasidagi qonli kurash, bo'rilar tomonidan boqib olingan San va shahzoda Asitaka qissasi.",
    poster_url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80",
    type: "Film",
    episodes: "1 / 1",
    current_episode: 1,
    total_episodes: 1,
    year: 1997,
    views_count: 140000,
    rating: 9.1,
    status: "Tugallangan",
    duration: "2 soat 14 daq.",
    age_rating: "13+",
    genres: ["Jangari", "Sarguzasht", "Fantaziya"],
    sub_available: true,
    dub_available: true,
    category: "filmlar",
    telegram_code: "anime_mononoke",
    metadata: { studio: "Studio Ghibli" }
  },

  // --- TASODIFIY ---
  {
    id: 23,
    slug: "sevgilim-kozoynagini-unutdi",
    title: "Sevgilim ko'zoyn...",
    original_title: "Suki na Ko ga Megane wo Wasureta",
    russian_title: "Моя возлюбленная забыла свои очки",
    description: "Kaidening partadoshi Mie doimo ko'zoynagini unutib qoldiradi. Kaide unga har qadamda mehr bilan yordam beradi va ular bir-birlariga yaqinlashadilar.",
    poster_url: "https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80",
    type: "TV serial",
    episodes: "13 / 13",
    current_episode: 13,
    total_episodes: 13,
    year: 2023,
    views_count: 51000,
    rating: 7.9,
    status: "Tugallangan",
    duration: "24 daq.",
    age_rating: "12+",
    genres: ["Komediya", "Romantika", "Maktab"],
    sub_available: true,
    dub_available: true,
    category: "tasodifiy",
    telegram_code: "anime_megane_wasureta",
    metadata: { studio: "GoHands" }
  },
  {
    id: 24,
    slug: "mexanik-qollar",
    title: "Mexanik qo'llar",
    original_title: "Mecha-Ude: Mechanical Arms",
    russian_title: "Механические руки",
    description: "Oddiy maktab o'quvchisi Hikaru tasodifan kiyimi bilan birlashib ketgan qobiliyatli kiber-qurol Armani uchratadi va sirli guruhlarga qarshi jangga kirishadi.",
    poster_url: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80",
    type: "TV serial",
    episodes: "12 / 12",
    current_episode: 12,
    total_episodes: 12,
    year: 2024,
    views_count: 29000,
    rating: 7.8,
    status: "Tugallangan",
    duration: "24 daq.",
    age_rating: "13+",
    genres: ["Jangari", "Ilmiy-fantastika"],
    sub_available: true,
    dub_available: true,
    category: "tasodifiy",
    telegram_code: "anime_mecha_ude",
    metadata: { studio: "TriF Studio" }
  },
  {
    id: 25,
    slug: "ozga-dunyoda-yol-topish",
    title: "O'zga dunyoda y...",
    original_title: "Isekai de Cheat Skill wo Te ni Shita Ore wa",
    russian_title: "Я получил читерские способности в другом мире",
    description: "Xo'rlangan yigit bobosining sirli eshigini ochib o'zga dunyoga o'tadi va u yerdagi mislsiz kuchlar bilan ikki dunyo orasida yangi hayot boshlaydi.",
    poster_url: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    type: "TV serial",
    episodes: "13 / 13",
    current_episode: 13,
    total_episodes: 13,
    year: 2023,
    views_count: 94000,
    rating: 8.2,
    status: "Tugallangan",
    duration: "24 daq.",
    age_rating: "16+",
    genres: ["Jangari", "Fantaziya", "Isekai"],
    sub_available: true,
    dub_available: true,
    category: "tasodifiy",
    telegram_code: "anime_isekai_cheat",
    metadata: { studio: "Millepensee" }
  },
  {
    id: 26,
    slug: "mening-qiz-dostlarim",
    title: "Mening qiz do'stli...",
    original_title: "Kanojo, Okarishimasu / Ame wo Tsugeru Hyouryuu Danchi",
    russian_title: "Дрейфующий дом",
    description: "Bolalikdagi do'stlar buzilishi rejalashtirilgan eski ko'p qavatli uyda sirli tarzda cheksiz dengizda suzib yurgan holda uyg'onadilar.",
    poster_url: "https://images.unsplash.com/photo-1516331138075-f3adc1e149cd?w=600&auto=format&fit=crop&q=80",
    type: "Film",
    episodes: "1 / 1",
    current_episode: 1,
    total_episodes: 1,
    year: 2022,
    views_count: 67000,
    rating: 8.1,
    status: "Tugallangan",
    duration: "2 soat",
    age_rating: "12+",
    genres: ["Drama", "Fantaziya", "Sarguzasht"],
    sub_available: true,
    dub_available: true,
    category: "tasodifiy",
    telegram_code: "anime_hyouryuu_danchi",
    metadata: { studio: "Studio Colorido" }
  }
];
